"""empty message

Revision ID: 041a1de8b693
Revises: 
Create Date: 2020-05-25 21:27:25.709613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '041a1de8b693'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('uuid', sa.String(length=11), nullable=False),
    sa.Column('password', sa.String(length=15), nullable=False),
    sa.Column('user_type', sa.Enum('student', 'teacher', 'admin'), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('student_info',
    sa.Column('stu_id', sa.String(length=10), nullable=False),
    sa.Column('stu_name', sa.String(length=20), nullable=False),
    sa.Column('phone_number', sa.String(length=11), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.Column('uuid', sa.String(length=11), nullable=False),
    sa.ForeignKeyConstraint(['uuid'], ['user.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('stu_id')
    )
    op.create_table('teacher_info',
    sa.Column('teacher_id', sa.String(length=10), nullable=False),
    sa.Column('teacher_name', sa.String(length=20), nullable=False),
    sa.Column('phone_number', sa.String(length=11), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.Column('uuid', sa.String(length=11), nullable=False),
    sa.ForeignKeyConstraint(['uuid'], ['user.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('teacher_id')
    )
    op.create_table('course_info',
    sa.Column('course_id', sa.String(length=10), nullable=False),
    sa.Column('course_name', sa.String(length=40), nullable=False),
    sa.Column('course_intro', sa.String(length=100), nullable=True),
    sa.Column('teacher_id', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_info.teacher_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('check_in_task',
    sa.Column('task_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.String(length=10), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course_info.course_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('sc',
    sa.Column('course_id', sa.String(length=10), nullable=False),
    sa.Column('stu_id', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course_info.course_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stu_id'], ['student_info.stu_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('course_id', 'stu_id')
    )
    op.create_table('check_in_record',
    sa.Column('record_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stu_id', sa.String(length=10), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['stu_id'], ['student_info.stu_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['check_in_task.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('check_in_record')
    op.drop_table('sc')
    op.drop_table('check_in_task')
    op.drop_table('course_info')
    op.drop_table('teacher_info')
    op.drop_table('student_info')
    op.drop_table('user')
    # ### end Alembic commands ###
